# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
map ctrl+c copy_to_clipboard
map ctrl+v paste_from_clipboard

# Startgröße in Terminalzellen (columns x rows)
initial_window_width  120c
initial_window_height 32c
remember_window_size no

# Nerd Font für Icons
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic

